export  const ContextMenuItems = [
    {
      id: "cambridgeDictionary",
      name: "Cambridge Dictionary",
      url: "https://dictionary.cambridge.org/dictionary/english-chinese-traditional/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
    },
    {
      id: "cambridgeDictionaryEn",
      name: "Cambridge Dictionary (English)",
      url: "https://dictionary.cambridge.org/dictionary/english/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
    },
    {
      id:"merriamWebsterDictionary",
      name: "Merriam Webster Dictionary",
      url: "https://www.merriam-webster.com/dictionary/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
    },
    {
      id:"longmanDictionary",
      name: "Longman Dictionary Dictionary",
      url: "https://www.ldoceonline.com/dictionary/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
    },
    {
      id: "collinsDictionary",
      name: "Collins Dictionary",
      url: "https://www.collinsdictionary.com/dictionary/english/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
    },
    {
      id:"oxfordDictionary",
      name: "Oxford Dictionary",
      url: "https://www.oxfordlearnersdictionaries.com/definition/english/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
    },
    {
      id: "yahooDictionary",
      name: "Yahoo Dictionary",
      url: "https://tw.dictionary.search.yahoo.com/search?p=",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
    },
    {
      id: "youGlish",
      name: "YouGlish",
      url: "https://youglish.com/search/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
    },
  ];