export  const ContextMenuItems = [
    // GPT 3.5 
    {
      id: "wordExplorerGPT3_5",
      name: "Word Explorer ChatGPT 3.5",
      url: "https://chat.openai.com/?q=請幫我解釋以下這個英文單字的詞義、詞性、拼英 (使用美式發音 的 kk 音標)、音節 (顯示切分方式)，並給出五個句子 (英中對照)，",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 1200,
      height: 700,
    },
    // 線上字典
    {
      id: "cambridgeDictionary",
      name: "Cambridge Dictionary",
      url: "https://dictionary.cambridge.org/dictionary/english-chinese-traditional/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 800,
      height: 600,
    },
    {
      id: "cambridgeDictionaryEn",
      name: "Cambridge Dictionary (English)",
      url: "https://dictionary.cambridge.org/dictionary/english/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 800,
      height: 600,
    },
    {
      id:"merriamWebsterDictionary",
      name: "Merriam Webster Dictionary",
      url: "https://www.merriam-webster.com/dictionary/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 800,
      height: 600,
    },
    {
      id:"oxfordDictionary",
      name: "Oxford Dictionary",
      url: "https://www.oxfordlearnersdictionaries.com/definition/english/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 800,
      height: 600,
    },
    {
      id: "vocabulary",
      name: "Vocabulary",
      url: "https://www.vocabulary.com/dictionary/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 800,
      height: 600,
    },
    {
      id:"longmanDictionary",
      name: "Longman Dictionary Dictionary",
      url: "https://www.ldoceonline.com/dictionary/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 800,
      height: 600,
    },
    {
      id: "yahooDictionary",
      name: "Yahoo Dictionary",
      url: "https://tw.dictionary.search.yahoo.com/search?p=",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 800,
      height: 600,
    },

    // ChatGPT 的自製 GPT
    {
      id: "wordExplorer",
      name: "Word Explorer GPT",
      url: "https://chat.openai.com/g/g-XeTkWy0Bi-word-explorer?q=",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 1200,
      height: 700,
    },
    {
      id:"translationMaster",
      name: "Translation Master GPT",
      url: "https://chat.openai.com/g/g-6KpqlNuJe-translation-master?q=",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 1200,
      height: 700,
    },
    {
      id: "letterReplyAssistant",
      name: "Letter Reply Assistant GPT",
      url: "https://chat.openai.com/g/g-QqRVKynIZ-letter-reply-assistant?q=",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 1200,
      height: 700,
    },
    // 整段翻譯
    {
      id: "googleTranslate",
      name: "Google Translate",
      url: "https://translate.google.com/?sl=auto&tl=zh-TW&text=",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 1000,
      height: 600,
    },
    {
      id: "deepl",
      name: "Deepl",
      url: "https://www.deepl.com/translator#en/zh/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 1000,
      height: 600,
    },

    // 有單字發音的影片或音檔
    {
      id: "collinsDictionary",
      name: "Collins Dictionary",
      url: "https://www.collinsdictionary.com/dictionary/english/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 800,
      height: 600,
    },
    {
      id:"forvo",
      name: "Forvo",
      url: "https://forvo.com/search/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 800,
      height: 600,
    },
    {
      id: "voiceTube",
      name: "VoiceTube",
      url: "https://tw.voicetube.com/definition/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 800,
      height: 600,
    },
    {
      id: "youGlish",
      name: "YouGlish",
      url: "https://youglish.com/search/",
      title: "Search '%s' in",
      contexts: ["selection"],
      visible: true,
      openingMethod: 'popup',
      width: 800,
      height: 600,
    },


  ];